package view;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Cristian Stedile
 */
public class FConsPasto extends javax.swing.JDialog {

    /**
     * Creates new form FConsAnimal
     */
    public FConsPasto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPastos = new javax.swing.JTable();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btRocar = new javax.swing.JButton();
        btAdubar = new javax.swing.JButton();
        btSobSemeadura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Animais");
        setResizable(false);

        tbPastos.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        tbPastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbPastos.setRowHeight(30);
        tbPastos.setShowHorizontalLines(true);
        tbPastos.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tbPastos);

        btEditar.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btEditar.setText("EDITAR");

        btExcluir.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btExcluir.setText("EXCLUIR");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btRocar.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btRocar.setText("ROÇAR");
        btRocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRocarActionPerformed(evt);
            }
        });

        btAdubar.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btAdubar.setText("ADUBAR");
        btAdubar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdubarActionPerformed(evt);
            }
        });

        btSobSemeadura.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btSobSemeadura.setText("REALIZAR SOB SEMEADURA");
        btSobSemeadura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSobSemeaduraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSobSemeadura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAdubar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRocar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar)
                    .addComponent(btExcluir)
                    .addComponent(btRocar)
                    .addComponent(btAdubar)
                    .addComponent(btSobSemeadura))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btRocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRocarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRocarActionPerformed

    private void btAdubarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdubarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdubarActionPerformed

    private void btSobSemeaduraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSobSemeaduraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSobSemeaduraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAdubar;
    public javax.swing.JButton btEditar;
    public javax.swing.JButton btExcluir;
    public javax.swing.JButton btRocar;
    public javax.swing.JButton btSobSemeadura;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbPastos;
    // End of variables declaration//GEN-END:variables
}
