/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author crist
 */
public class FPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FPrincipal.class.getName());

    /**
     * Creates new form FPrincipal2
     */
    public FPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miInventario = new javax.swing.JMenuItem();
        miCadAnimal = new javax.swing.JMenuItem();
        miBaixas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miPesagens = new javax.swing.JMenuItem();
        miCadPesagem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miPastos = new javax.swing.JMenuItem();
        miCadPasto = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miMedicacao = new javax.swing.JMenuItem();
        miCadMedicacao = new javax.swing.JMenuItem();
        miAplicações = new javax.swing.JMenuItem();
        miCadAplicação = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        miSemens = new javax.swing.JMenuItem();
        miCadSemen = new javax.swing.JMenuItem();
        miInseminacoes = new javax.swing.JMenuItem();
        miCadInseminacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cow Gest 1.0");
        setResizable(false);

        jMenu1.setText("Animais");

        miInventario.setText("Inventário de Animais");
        jMenu1.add(miInventario);

        miCadAnimal.setText("Cadastro de Animal");
        jMenu1.add(miCadAnimal);

        miBaixas.setText("Baixas");
        jMenu1.add(miBaixas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pesagens de Leite");

        miPesagens.setText("Pesagens");
        jMenu2.add(miPesagens);

        miCadPesagem.setText("Cadastro de Pesagem");
        jMenu2.add(miCadPesagem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pastos");

        miPastos.setText("Pastos");
        jMenu3.add(miPastos);

        miCadPasto.setText("Cadastro de Pasto");
        jMenu3.add(miCadPasto);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Saúde Animal");

        miMedicacao.setText("Medicações");
        jMenu4.add(miMedicacao);

        miCadMedicacao.setText("Cadastro de Medicação");
        jMenu4.add(miCadMedicacao);

        miAplicações.setText("Aplicações");
        jMenu4.add(miAplicações);

        miCadAplicação.setText("Cadastro de Aplicação de Medicação");
        jMenu4.add(miCadAplicação);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reprodução");

        miSemens.setText("Sêmens");
        jMenu5.add(miSemens);

        miCadSemen.setText("Cadastro de Sêmen");
        jMenu5.add(miCadSemen);

        miInseminacoes.setText("Inseminações");
        jMenu5.add(miInseminacoes);

        miCadInseminacao.setText("Cadastro de Inseminação");
        jMenu5.add(miCadInseminacao);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem miAplicações;
    public javax.swing.JMenuItem miBaixas;
    public javax.swing.JMenuItem miCadAnimal;
    public javax.swing.JMenuItem miCadAplicação;
    public javax.swing.JMenuItem miCadInseminacao;
    public javax.swing.JMenuItem miCadMedicacao;
    public javax.swing.JMenuItem miCadPasto;
    public javax.swing.JMenuItem miCadPesagem;
    public javax.swing.JMenuItem miCadSemen;
    public javax.swing.JMenuItem miInseminacoes;
    public javax.swing.JMenuItem miInventario;
    public javax.swing.JMenuItem miMedicacao;
    public javax.swing.JMenuItem miPastos;
    public javax.swing.JMenuItem miPesagens;
    public javax.swing.JMenuItem miSemens;
    // End of variables declaration//GEN-END:variables
}
